server:
  port: 8890

spring:
  jpa:
    open-in-view: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  datasource:
    url: jdbc:mysql://47.101.171.252:3306/imagesServer
    username: root
    password: admin