server:
  port: 8890

spring:
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB
  jpa:
    open-in-view: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  datasource:
    url: jdbc:mysql://47.101.171.252:3306/imagesServer?useUnicode=true&characterEncoding=UTF-8
    username: admin
    password: ly19980527

